services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    mem_limit: 256m
    restart: always

  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      - DOMAINS
      - STAGE
      - CLIENT_MAX_BODY_SIZE
    volumes:
      - https_portal_data:/var/lib/https-portal

  n8n:
    build: .
    container_name: n8n
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - GENERIC_TIMEZONE=Asia/Tokyo
      - N8N_COMMUNITY_NODES_ENABLED=true
      - N8N_ENCRYPTION_KEY
      - N8N_HOST
      - N8N_SECURE_COOKIE
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=14
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=50000
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
      - ./files:/home/node/files
      - ./local-files:/tmp/local-files
volumes:
  n8n_data:
  postgres_data:
  https_portal_data:
